version: "3.9"

services:
  fradium-analyzer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    env_file:
      - .env

volumes:
  node_modules:
